# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170208_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.CharField(default='name', max_length=10),
            preserve_default=False,
        ),
    ]
